project:
  type: website
  output-dir: docs

website:
  title: "ChristinaDai_Quiz02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy & GDP
      - href: life-population.qmd
        text: Life Expectancy & Population
      - href: cambodia_analysis.qmd
        text: Cambodia Analysis
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
